[database]
url=jdbc:mysql://8.148.225.21:3306/stock?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
username=root
password=liuhuande123
driverClassName=com.mysql.cj.jdbc.Driver
;[application]
;thread = 32